### ISSUE TITLE
Commandline option to change fan policy on fly

### ISSUE THREAD

**Issue by Microwave-WYB** [TamtamHero/fw-fanctrl#1]
I wish we can do things like `fw-fanctrl lazy` or `fw-fanctrl medium`

**Comment by navyfighter12** [comment]
That would be great

**Comment by TamtamHero** [comment]
https://github.com/TamtamHero/fw-fanctrl/pull/7

**Comment by navyfighter12** [comment]
> #7

Nice!! Thank you!
