### ISSUE TITLE
[Question] about the ec tool project and the right version to use

### ISSUE THREAD

**Issue by leopoldhub** [TamtamHero/fw-fanctrl#27]
Hi there,

As stated in this project README, fw-fanctrl
> uses [fw-ectool](https://github.com/DHowett/fw-ectool) to change parameters in FrameWork's embedded controller (EC).

the link refers to the [DHowett/fw-ectool](https://github.com/DHowett/fw-ectool) project, which is a fork of the Framework team's [FrameworkComputer/EmbeddedController](https://github.com/FrameworkComputer/EmbeddedController) project.

The main concern here is that the [DHowett/fw-ectool](https://github.com/DHowett/fw-ectool) project is a whopping [10098 commits behind](https://github.com/DHowett/framework-ec/compare/main...FrameworkComputer%3AEmbeddedController%3Amain) the official project.

I imagine that there are reasons for using [DHowett/fw-ectool](https://github.com/DHowett/fw-ectool) instead of [FrameworkComputer/EmbeddedController](https://github.com/FrameworkComputer/EmbeddedController), but I cannot seem to find any information or documentation about it either in [DHowett/fw-ectool](https://github.com/DHowett/fw-ectool) or in this project and would appreciate a bit of context about this choice.

Thank you and have a great day.

**Comment by TamtamHero** [comment]
Yes, the project actually moved to Gitlab: https://gitlab.howett.net/DHowett/ectool
I forgot to update the link in the readme, I'm on it

**Comment by leopoldhub** [comment]
Thank you @TamtamHero , btw you forgot the first link of the readme in your last commit :)

> Under the hood, it uses [fw-ectool](https://github.com/DHowett/fw-ectool) to change parameters in FrameWork's embedded controller (EC).
