### ISSUE TITLE
Usage of pipfile for requirements.txt replacement

### ISSUE THREAD

**Issue by leopoldhub** [TamtamHero/fw-fanctrl#32]
Hi,

Would you be in favor of using [pipfile](https://github.com/pypa/pipfile) for dependency management over the traditional `requirements.txt`?
This would mainly allow us to keep production and dev dependencies separate, as well as requiring a minimum Python version.

Here is the [documentation](https://pipenv.pypa.io/zh-cn/stable/basics.html) if you want to know more about it.

**Comment by TamtamHero** [comment]
Actually, I merged #29 without realizing that `requirements.txt` is now empty. Very satisfying.
Shouldn't we simply remove it, update the install script to remove the pip call and try our best to never add dependencies in the future, rather that adding unused boilerplate for pipfile ?

**Comment by leopoldhub** [comment]
We could remove it for now, but having the possibility to add dev dependencies for code quality would be nice too

**Comment by TamtamHero** [comment]
Ok, be my guest then

**Comment by leopoldhub** [comment]
irrelevant for now as we do not have the need for libraries yet.
Might re-open later if needed.
