### ISSUE TITLE
No binary embedding

### ISSUE THREAD

**Issue by leopoldhub** [TamtamHero/fw-fanctrl#39]
Hi, as stated [here](https://github.com/TamtamHero/fw-fanctrl/pull/29#issuecomment-2117459541) by @dariov1988 , we should not embed binaries into the project, but rather fetch them from the official source.

The build artifacts for ectool can be found [here](https://gitlab.howett.net/DHowett/ectool/-/artifacts).

This is an open question:
Do you have any recommendations on how we should fetch, extract and install the artifacts for this project?

**Comment by blu3r4d0n** [comment]
I think there's also [https://search.nixos.org/packages?channel=24.05&show=fw-ectool&from=0&size=50&sort=relevance&type=packages&query=fw-ectool](url)

**Comment by leopoldhub** [comment]
done in #51
