### ISSUE TITLE
[BUG] [packaging/AUR] Sleep hook causes 90-second hang on startup / resume from sleep

### ISSUE THREAD

**Issue by rothn** [TamtamHero/fw-fanctrl#48]
**Describe the bug**
Sleep hook causes a hang when coming out of suspend. Also reported at https://github.com/systemd/systemd/issues/33020 and https://bbs.archlinux.org/viewtopic.php?pid=2177336#p2177336.

**To Reproduce**
1. Install the package
2. Reboot
3. Observe a delay of exactly 90 seconds coming out of sleep.

**Expected behavior**
The system should resume from sleep instantly.

**Screenshots**

**Error message**
```txt
Jun 10 22:40:56 <REDACTED> runuser[56917]: pam_unix(runuser-l:session): session opened for user root(uid=0) by root(uid=0)
Jun 10 22:41:26 <REDACTED> runuser[56812]: pam_systemd(runuser-l:session): Failed to create session: Connection timed out
Jun 10 22:41:26 <REDACTED> runuser[56812]: pam_unix(runuser-l:session): session closed for user root
```

**Environment (please complete the following information):**
 - OS: Arch
 - Version commit c9397ab
 - Configuration file NA
 - Installation method `yay -S fw-fanctrl-git`

**Additional context**
Removing the sleep hook solves the problem.

**Comment by rothn** [comment]
Confirmed fixed as of 1bc4f60

**Comment by leopoldhub** [comment]
Hi, sorry for the delay, I hope you are doing well.

We recently did a massive code cleanup which included removing the use of `runuser` which was causing problems for some users.
Seeing that it is fixed in the head commit, it seems that it is indeed the same issue as #13 .

Is there anything else I can help you with?

**Comment by rothn** [comment]
No-- this is confirmed fix after your cleanup. Thanks for your work!
