### ISSUE TITLE
Is there a way to fully disable this tool and resort to the default fan control?

### ISSUE THREAD

**Issue by DeflateAwning** [TamtamHero/fw-fanctrl#53]
Is there a way to fully disable this tool and resort to the default fan control (without uninstalling)? 

If there is, it would be awesome to include it in the README.

If there's not, allow this to be a feature request for such a feature.

**Comment by leopoldhub** [comment]
Hi, yes there is

You can:
- pause the program with `fw-fanctrl --pause`
- stop the systemd service with `systemctl stop fw-fanctrl.service` / disable it for future restarts with `systemd disable fw-fanctrl.service`

The pause command is documented in the README.md file.

Is this what you were looking for, or can I help you with anything else?

**Comment by DeflateAwning** [comment]
Are those two bullet point list items joined by an "and" or an "or"?

Like, does each item do the same thing, or do you need to do both items?

**Comment by DeflateAwning** [comment]
Perhaps a better description of the `--pause` action (which currently reads "temporarily disable the service") would be:

> temporarily disable the service and use the embedded controller's temperature control

The idea of "disabling the fan controller" is a bit of a scary action, without explictly confirming that there is indeed another tool that manages it

**Comment by leopoldhub** [comment]
Hi, it can indeed be confusing.

Does this solves the issue?
