### ISSUE TITLE
[BUG] Is libftdi1 dependency missing?

### ISSUE THREAD

**Issue by Lunarmagpie** [TamtamHero/fw-fanctrl#68]
**Describe the bug**
When I ran the program I got the error that libftdi1.so.2 was not installed.

**To Reproduce**
Install on system without libftdi1.

**Expected behavior**
I believe this library should be mentioned in the README because it is a dependency of the program.

**Environment (please complete the following information):**
 - OS: Debian Trixie
- Commit: b4f87b

**Comment by leopoldhub** [comment]
Hi, thanks for bringing this to our attention.

I suspect that this is a ectool dependency.
Could you please give in more detail about when you got this error message?

**Comment by Lunarmagpie** [comment]
Hello,
I did not install ectool manually before using this program. Im not sure what other context to add but if you have any questions I am happy to answer :)

**Comment by leopoldhub** [comment]
No problem,

Since interface with the ectool and do not manually interract with the hardware, I think that this is an ectool dependency.

I will check to see if it is listed on the github, if not I will add it as a sub-dependency in the readme.

**Comment by saizo80** [comment]
based on the aur page, libftdi is a runtime dependency of ectool
https://aur.archlinux.org/packages/fw-ectool-git

**Comment by leopoldhub** [comment]
Indeed, I added it as a ectool sub-dependency in the documentation.

Have a nice day.
