### ISSUE TITLE
[BUG] Error getting I/O privilege: Operation not permitted

### ISSUE THREAD

**Issue by C0Nd3Mnd** [TamtamHero/fw-fanctrl#81]
**Describe the bug**
Running the software gives me the errors I shared below, with the software seemingly not working and the system using the default fan curve instead. I'm pretty sure it was working as intended before, but now it's showing these errors.

**To Reproduce**
1. After installation, wait for the service to start.

**Expected behavior**
Fan control working as configured with no errors in the log.

**Screenshots**

**Error message**
_(from `systemctl status fw-fanctrl`)_
```txt
Aug 27 15:20:25 bird-framework python3[9725]: Unable to establish host communication
Aug 27 15:20:25 bird-framework python3[9725]: Couldn't find EC
Aug 27 15:20:25 bird-framework python3[9731]: Error getting I/O privilege: Operation not permitted
Aug 27 15:20:25 bird-framework python3[9731]: Cannot find I2C adapter
Aug 27 15:20:25 bird-framework python3[9731]: Unable to establish host communication
Aug 27 15:20:25 bird-framework python3[9731]: Couldn't find EC
Aug 27 15:20:26 bird-framework python3[9737]: Error getting I/O privilege: Operation not permitted
Aug 27 15:20:26 bird-framework python3[9737]: Cannot find I2C adapter
Aug 27 15:20:26 bird-framework python3[9737]: Unable to establish host communication
Aug 27 15:20:26 bird-framework python3[9737]: Couldn't find EC
```

**Environment (please complete the following information):**
 - OS: Fedora 40 KDE Spin, kernel 6.10.6
 - Hardware: Framework 13 Core Ultra Series 1
 - Version 2a9828f
 - Configuration file [config.json]
```json
{
    "defaultStrategy": "bird",
    "strategyOnDischarging" : "",
    "strategies": {
        "bird": {
            "fanSpeedUpdateFrequency": 5,
            "movingAverageInterval": 40,
            "speedCurve": [
                { "temp": 0, "speed": 0 },
                { "temp": 65, "speed": 0 },
                { "temp": 75, "speed": 50 },
                { "temp": 90, "speed": 100 }
            ]
        },
        "laziest": {
            "fanSpeedUpdateFrequency": 5,
            "movingAverageInterval": 40,
            "speedCurve": [
                { "temp": 0, "speed": 0 },
                { "temp": 45, "speed": 0 },
                { "temp": 65, "speed": 25 },
                { "temp": 70, "speed": 35 },
                { "temp": 75, "speed": 50 },
                { "temp": 85, "speed": 100 }
            ]
        },
        "lazy": {
            "fanSpeedUpdateFrequency": 5,
            "movingAverageInterval": 30,
            "speedCurve": [
                { "temp": 0, "speed": 15 },
                { "temp": 50, "speed": 15 },
                { "temp": 65, "speed": 25 },
                { "temp": 70, "speed": 35 },
                { "temp": 75, "speed": 50 },
                { "temp": 85, "speed": 100 }
            ]
        },
        "medium": {
            "fanSpeedUpdateFrequency": 5,
            "movingAverageInterval": 30,
            "speedCurve": [
                { "temp": 0, "speed": 15 },
                { "temp": 40, "speed": 15 },
                { "temp": 60, "speed": 30 },
                { "temp": 70, "speed": 40 },
                { "temp": 75, "speed": 80 },
                { "temp": 85, "speed": 100 }
            ]
        },
        "agile": {
            "fanSpeedUpdateFrequency": 3,
            "movingAverageInterval": 15,
            "speedCurve": [
                { "temp": 0, "speed": 15 },
                { "temp": 40, "speed": 15 },
                { "temp": 60, "speed": 30 },
                { "temp": 70, "speed": 40 },
                { "temp": 75, "speed": 80 },
                { "temp": 85, "speed": 100 }
            ]
        },
        "very-agile": {
            "fanSpeedUpdateFrequency": 2,
            "movingAverageInterval": 5,
            "speedCurve": [
                { "temp": 0, "speed": 15 },
                { "temp": 40, "speed": 15 },
                { "temp": 60, "speed": 30 },
                { "temp": 70, "speed": 40 },
                { "temp": 75, "speed": 80 },
                { "temp": 85, "speed": 100 }
            ]
        },
        "deaf": {
            "fanSpeedUpdateFrequency": 2,
            "movingAverageInterval": 5,
            "speedCurve": [
                { "temp": 0, "speed": 20 },
                { "temp": 40, "speed": 30 },
                { "temp": 50, "speed": 50 },
                { "temp": 60, "speed": 100 }
            ]
        },
        "aeolus": {
            "fanSpeedUpdateFrequency": 2,
            "movingAverageInterval": 5,
            "speedCurve": [
                { "temp": 0, "speed": 20 },
                { "temp": 40, "speed": 50 },
                { "temp": 65, "speed": 100 }
            ]
        }
    }
}
```
 - Installation method [full command)/package manager/other...]: repo/git clone + `install.sh`

**Additional context**

**Comment by leopoldhub** [comment]
Hi, it looks like a permission error.
Could you try running the following command as sudo manually?
`ectool autofanctrl`

If this does not return an error, can you make sure that the systemctl service is running as a sudo user?

**Comment by C0Nd3Mnd** [comment]
> Hi, it looks like a permission error. Could you try running the following command as sudo manually? `ectool autofanctrl`

This outputs the same:

```txt
❯ sudo ectool autofanctrl
Place your right index finger on the fingerprint reader
Error getting I/O privilege: Operation not permitted
Cannot find I2C adapter
Unable to establish host communication
Couldn't find EC
```

**Comment by leopoldhub** [comment]
Strange...
The fact that the error occurs as a sudo user directly with the ectool suggests that this is not a script issue, but possibly an ectool one, or a missing configuration/dependency.

Can you check that you have libftdi1.so.2 correctly installed on your system correctly?

Also, are you sure that the service worked before, and on what date/version?

**Comment by C0Nd3Mnd** [comment]
I just checked `dmesg` and it outputs these messages:

```txt
[ 1666.707297] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1666.715398] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1666.721563] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1666.727303] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1667.331788] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1667.737055] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1667.745397] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
[ 1668.754372] Lockdown: ectool: raw io port access is restricted; see man kernel_lockdown.7
```

I can't 100% confirm whether or not this worked previously, it seemed like it was working judging by how different the fan curve feels like now. I must've been running commit 6d2d3de, as I didn't have this device for more than a few days (it's the new Core Ultra model). There have been a couple of Fedora package updates, so maybe that broke something.

Reading `man kernel_lockdown.7` I understand that this permission denial seems to be "by design", but I'm not sure how to make an exception without completely disabling this feature (not sure whether I should).

**Comment by leopoldhub** [comment]
As far as I know, we always used ectool to control fan speed, so if it worked then, it should now. (And no massive rework of the core system in the last two month)

I seems like a Fedora configuration/security?
Did you disable secure boot as mentioned in the installation procedure?

**Comment by C0Nd3Mnd** [comment]
Ah, I somehow managed to miss this hint in the installation instructions both when first installing `fw-fanctrl` and now then again when checking the instructions again before creating this issue. Yup, with disabled secure boot it indeed works. I must've just imagined it working before then.

Closing this then as it doesn't seem like this is something that can be worked around easily from the side of this tool.

**Comment by leopoldhub** [comment]
Glad to see that this has been resolved!

I will add a question about the SecureBoot to the issue templates to try and resolve these types of issues before they are created.

Have a nice day.
