### ISSUE TITLE
The default profile seems extreme

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [TamtamHero/fw-fanctrl#86]
Thank you for creating this software.

I am using it (on a F-13 AMD, under Linux Mint 22 Cinnamon) and I find:

- mostly, and even under moderate load, the fans are off (or at least inaudible);
- when under heavy load the fans are very loud and then, when the load lightens, turn off completely.

In short, the default program seems to be all-or-nothing. I would prefer, as too I imagine would various others, something more moderate. You do [provide some advice on creating a profile](https://github.com/TamtamHero/fw-fanctrl/blob/main/doc/configuration.md), but I would welcome some (extra) help. Thanks.

**Comment by Svenum** [comment]
The structure of the config file is not very difficult. Just look at the default (https://github.com/TamtamHero/fw-fanctrl/blob/main/config.json) and try to understand it.  If you need even more help, please let me know.

@TamtamHero 
I think every Framework version needs an other fancurve as every has slight different cooling.Maybe we could create an fancurve per Framework version? This will need much help from the community as we does not own every version. At least I dont have the money... :joy:

**Comment by LinuxOnTheDesktop** [comment]
@Svenum 
I was in too much of a rush; I see, now, the following. I can switch easily between fan profiles that are fairly self-explanatory. Moreover, I can create a new profile easily. Good stuff. I'll start by trying the 'medium' profile.

**Comment by Svenum** [comment]
Please give us feedback witch profile you used at the end, and if you create a own please write this too.
The output off `dmidecode | grep "Product Name"` (maybe sudo needed) would be nice too.

With this informations we could create a list with recommended profiles for each Framework product.

**Comment by TamtamHero** [comment]
I'll be honest, the default profile is the one I use. I think that there is no profile that will fit every case, as it depends on many factors. Some factors can be grouped (like, which framework laptop do you own ?) but some others vary from place and time (Where do you live ? Which season is it currently ? Do you have AC ?).
For instance, in French summer, I use the `medium` strategy, but the rest of the time I use the default one. Was I to live in Saudi Arabia, I would certainly do otherwise. So, I guess it's unavoidable that every user has to take a look at strategies and pick/create the right one for his case.

I wonder how big players like Apple do tackle this issue.
Maybe they have a target temperature for any given tuple [laptop model, cpu usage, cpu frequency] and run a PID control loop on the fan to maintain this temperature.
That would probably work better. But that's quite some work :sleeping:

**Comment by LinuxOnTheDesktop** [comment]
> Please give us feedback witch profile you used at the end, and if you create a own please write this too.

Here is what I am using. Therein, the 'ac' profile has had a fair amount of testing. The 'bat' profile I have tested less.

```
"defaultStrategy": "me_ac",
"strategyOnDischarging" : "me_bat",

[. . . .]

"me_ac": {
    "fanSpeedUpdateFrequency": 4,
    "movingAverageInterval": 15,
    "speedCurve": [
        { "temp": 0, "speed": 10 },
        { "temp": 45, "speed": 15 },
        { "temp": 53, "speed": 20 },
        { "temp": 57, "speed": 25 },
        { "temp": 60, "speed": 30 },
        { "temp": 65, "speed": 35 },
        { "temp": 70, "speed": 45 },
        { "temp": 75, "speed": 70 },
        { "temp": 80, "speed": 85 },
        { "temp": 85, "speed": 90 },
        { "temp": 90, "speed": 100 }
    ]
},
"me_bat": {
    "fanSpeedUpdateFrequency": 6,
    "movingAverageInterval": 20,
    "speedCurve": [
        { "temp": 0, "speed": 15 },
        { "temp": 45, "speed": 15 },
        { "temp": 55, "speed": 20 },
        { "temp": 60, "speed": 25 },
        { "temp": 65, "speed": 40 },
        { "temp": 70, "speed": 50 },
        { "temp": 75, "speed": 70 },
        { "temp": 80, "speed": 80 },
        { "temp": 85, "speed": 95 },
        { "temp": 90, "speed": 100 }
    ]

```
My aims with those two custom profiles are as follows.

1. Have a quiet computer.
2. Not have the fans whirr up just for a moment (as, crazily, they do with my Framework-13 out-of-the-box - and even within the BIOS!).
3. Not push my luck by letting the computer get _very_ hot.

Perhaps my profiles could be (re)named 'sanelyQuiet_ac' and 'sanelyQuiet_bat' (!).

```
# dmidecode | grep "Product Name"
	Product Name: Laptop 13 (AMD Ryzen 7040Series)
	Product Name: FRANMDCP05
```
