### ISSUE TITLE
[BUG] Failure to Authenticate `pwmgetfanrpm`

### ISSUE THREAD

**Issue by avantbored** [TamtamHero/fw-fanctrl#90]
**Describe the bug**
Prompted to authenticate in order to run `/usr/bin/ectool/pmwgetfanrpm` as the superuser loops indefinitely. 

**To Reproduce**
1. Go to Gnome Extension homepage `fw-fanctrl`: https://extensions.gnome.org/extension/7053/fw-fanctrl/
2. Click on `Install`
3. Scroll down to Input password.
4. See error: Authentication is needed to run `/usr/bin/ectool/pwmgetfanrpm` as the superuser

**Expected behavior**
Authentication success and subsequent normal app behavior and function.

**Screenshots**

![Screenshot From 2024-11-07 07-50-02](https://github.com/user-attachments/assets/108a3722-40a2-43aa-8807-bcdcc88feb4b)

**Error message**
```Authentication is needed to run `/usr/bin/ectool/pwmgetfanrpm` as the superuser```

**Environment (please complete the following information):**
 - OS: EndeavourOS 
 - Version: rolling
 - Configuration file
[config.json](https://github.com/user-attachments/files/17665340/config.json)

 - Installation method: AUR; GNOME Extension

**Additional context**
GNOME 47.

`fw-fanctrl.service` running appropriately: 

```fw-fanctrl.service - Framework Fan Controller
     Loaded: loaded (/usr/lib/systemd/system/fw-fanctrl.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-11-07 08:15:46 PST; 1min 21s ago
 Invocation: 5479c0c1dba44f64a0dac3506e7fdd9b
   Main PID: 968 (python3)
      Tasks: 2 (limit: 76020)
     Memory: 9.9M (peak: 11.6M)
        CPU: 2.696s
     CGroup: /system.slice/fw-fanctrl.service
             └─968 /usr/bin/python3 /usr/bin/fw-fanctrl run --config /etc/fw-fanctrl/config.json --silent
```
Thank you!

**Comment by leopoldhub** [comment]
Hi, the GNOME extension is not affiliated with or managed by us in any way.

Please address this issue on their github repository.

https://github.com/joax/fw-fanctrl-gnome-shell-extension

Have a nice day.

**Comment by avantbored** [comment]
Thank you for your time and response!
